# example netlify.toml
[build]
  command = "npm run deploy-build"
  functions = "functions"
  publish = "_site"
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  [dev] 
   command = "npm run serve" # Command to start your dev server
  #  publish = "_site" # Folder with the static content for _redirect file
  #  targetPort = 8080
  #  port = 8082
   framework = "eleventy"

  [functions]
  node_bundler = "esbuild"
  [functions.opengraph-image-generator]
    external_node_modules = ["playwright-core"]

  [environment]
AWS_LAMBDA_JS_RUNTIME="nodejs14.x"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
