# example netlify.toml
[build]
  command = "npm run deploy-build"
  functions = "functions"
  publish = "_site"
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  [dev] 
   command = "npm run serve" # Command to start your dev server
  #  publish = "_site" # Folder with the static content for _redirect file
  #  targetPort = 8080
  #  port = 8082
   framework = "eleventy"

  [functions]
  node_bundler = "esbuild"
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
